[package]
name = "remy"
version = "0.1.0"
authors = ["Aaron Liberatore <aaron.liberatore@gmail.com>"]

[dependencies]
piston = "0.1.4"
piston2d-graphics = "0.1.4"
pistoncore-glutin_window = "0.1.0"
piston2d-opengl_graphics = "0.1.0"
